Scratch.extensions.register(new class{getInfo(){return{id:'blk138',docsURI:'https://learn.ccw.site/article/b48d6773-9847-480d-afb2-6b1fc22cf45c',blocks:[
{opcode:'used'},
'',
'<block type="procedures_definition"><statement name="custom_block"><block type="procedures_prototype"><mutation proccode="新建自定义积木" argumentids="[]" argumentnames="[]" argumentdefaults="[&quot;&quot;]" warp="true" global="null" return="null"/></block></statement></block>',
'<block type="procedures_call"><mutation proccode="// %s" argumentids="[&quot;_&quot;]" warp="true"/><value name="_"><shadow type="text"/></value></block>',
'运算',
'<block type="operator_equals"><value name="OPERAND1"><shadow type="text"/></value><value name="OPERAND2"><shadow type="text"/></value></block>',
'<block type="operator_gt"><value name="OPERAND1"><shadow type="text"/></value><value name="OPERAND2"><shadow type="text"/></value></block>',
'<block type="operator_lt"><value name="OPERAND1"><shadow type="text"/></value><value name="OPERAND2"><shadow type="text"/></value></block>',
'<block type="operator_not"><value name="OPERAND"><block type="operator_equals"><value name="OPERAND1"><shadow type="text"/></value><value name="OPERAND2"><shadow type="text"/></value></block></value></block>',
'<block type="operator_not"><value name="OPERAND"><block type="operator_gt"><value name="OPERAND1"><shadow type="text"/></value><value name="OPERAND2"><shadow type="text"/></value></block></value></block>',
'<block type="operator_not"><value name="OPERAND"><block type="operator_lt"><value name="OPERAND1"><shadow type="text"/></value><value name="OPERAND2"><shadow type="text"/></value></block></value></block>',
'',
'<block type="argument_editor_boolean"><field name="TEXT">1</field></block>',
'<block type="operator_not"><value name="OPERAND"><shadow type="argument_editor_boolean"><field name="TEXT"/></shadow></value></block>',
'<block type="operator_and"><value name="OPERAND1"><shadow type="argument_editor_boolean"><field name="TEXT"/></shadow></value><value name="OPERAND2"><shadow type="argument_editor_boolean"><field name="TEXT"/></shadow></value></block>',
'<block type="operator_or"><value name="OPERAND1"><shadow type="argument_editor_boolean"><field name="TEXT"/></shadow></value><value name="OPERAND2"><shadow type="argument_editor_boolean"><field name="TEXT"/></shadow></value></block>',
'',
'<block type="operator_subtract"><value name="NUM1"><block type="operator_multiply"><value name="NUM1"><shadow type="text"/></value><value name="NUM2"><shadow type="text"><field name="TEXT">2</field></shadow></value></block></value><value name="NUM2"><shadow type="text"><field name="TEXT">1</field></shadow></value></block>',
'',
'<block type="operator_mathop"><value name="NUM"><shadow type="text"/></value></block>',
'<block type="operator_add"><value name="NUM1"><shadow type="text"/></value><value name="NUM2"><shadow type="text"/></value></block>',
'<block type="operator_subtract"><value name="NUM1"><shadow type="text"/></value><value name="NUM2"><shadow type="text"/></value></block>',
'<block type="operator_multiply"><value name="NUM1"><shadow type="text"/></value><value name="NUM2"><shadow type="text"/></value></block>',
'<block type="operator_divide"><value name="NUM1"><shadow type="text"/></value><value name="NUM2"><shadow type="text"/></value></block>',
'',
'<block type="operator_mathop"><field name="OPERATOR">e ^</field><value name="NUM"><block type="operator_multiply"><value name="NUM1"><block type="operator_mathop"><field name="OPERATOR">ln</field><value name="NUM"><shadow type="text"/></value></block></value><value name="NUM2"><shadow type="text"><field name="TEXT">3</field></shadow></value></block></value></block>',
'<block type="operator_divide"><value name="NUM1"><block type="operator_mathop"><field name="OPERATOR">ln</field><value name="NUM"><shadow type="text"/></value></block></value><value name="NUM2"><block type="operator_mathop"><field name="OPERATOR">ln</field><value name="NUM"><shadow type="text"><field name="TEXT">2</field></shadow></value></block></value></block>',
'',
'<block type="operator_mod"><value name="NUM1"><shadow type="text"/></value><value name="NUM2"><shadow type="text"/></value></block>',
'<block type="operator_add"><value name="NUM1"><block type="operator_mod"><value name="NUM1"><block type="operator_subtract"><value name="NUM1"><shadow type="text"/></value><value name="NUM2"><shadow type="text"><field name="TEXT">1</field></shadow></value></block></value><value name="NUM2"><shadow type="text"/></value></block></value><value name="NUM2"><shadow type="text"><field name="TEXT">1</field></shadow></value></block>',
'',
'<block type="operator_round"><value name="NUM"><shadow type="text"/></value></block>',
'<block type="operator_mathop"><field name="OPERATOR">floor</field><value name="NUM"><shadow type="text"/></value></block>',
'<block type="operator_mathop"><field name="OPERATOR">ceiling</field><value name="NUM"><shadow type="text"/></value></block>',
'',
'<block type="operator_add"><value name="NUM1"><shadow type="math_angle"/></value><value name="NUM2"><shadow type="text"/></value></block>',
'<block type="operator_mathop"><field name="OPERATOR">cos</field><value name="NUM"><shadow type="text"/></value></block>',
'<block type="operator_mathop"><field name="OPERATOR">sin</field><value name="NUM"><shadow type="text"/></value></block>',
'<block type="operator_mathop"><field name="OPERATOR">atan</field><value name="NUM"><shadow type="text"/></value></block>',
'',
'<block type="operator_length"><value name="STRING"><shadow type="text"/></value></block>',
'<block type="operator_letter_of"><value name="STRING"><shadow type="text"/></value><value name="LETTER"><shadow type="text"/></value></block>',
'<block type="operator_join"><value name="STRING1"><shadow type="text"/></value><value name="STRING2"><shadow type="text"/></value></block>',
'<block type="operator_join"><value name="STRING1"><shadow type="text"/></value><value name="STRING2"><block type="operator_join"><value name="STRING1"><shadow type="text"><field name="TEXT">,\n</field></shadow></value><value name="STRING2"><shadow type="text"/></value></block></value></block>',
'<block type="operator_contains"><value name="STRING1"><shadow type="text"/></value><value name="STRING2"><shadow type="text"/></value></block>',
'',
'<block type="operator_join"><value name="STRING1"><shadow type="colour_picker"><field name="COLOUR">#59C059</field></shadow></value><value name="STRING2"><shadow type="text"/></value></block>',
'<block type="operator_round"><value name="NUM"><shadow type="note"><field name="NOTE">60</field></shadow></value></block>',
'<block type="matrix"><field name="MATRIX">0011101000010000100000111</field></block>',
'<block type="sensing_userid"/>',
'',
'控制',
'<block type="control_create_clone_of_menu"/>',
'<block type="control_start_as_clone"/>',
'<block type="control_create_clone_of"><value name="CLONE_OPTION"><shadow type="control_create_clone_of_menu"/></value></block>',
'<block type="control_delete_this_clone"/>',
'',
'<block type="control_all_at_once"><statement name="SUBSTACK"><shadow type="control_delete_this_clone"/></statement></block>',
'',
'<block type="control_if"><value name="CONDITION"><shadow type="argument_editor_boolean"><field name="TEXT"/></shadow></value></block>',
'<block type="control_if_else"><value name="CONDITION"><shadow type="argument_editor_boolean"><field name="TEXT"/></shadow></value></block>',
'',
'<block type="control_wait_until"><value name="CONDITION"><shadow type="argument_editor_boolean"><field name="TEXT"/></shadow></value></block>',
'<block id="while" type="control_while"><value name="CONDITION"><shadow type="argument_editor_boolean"><field name="TEXT"/></shadow></value></block>',
'<block type="control_repeat_until"><value name="CONDITION"><shadow type="argument_editor_boolean"><field name="TEXT"/></shadow></value></block>',
'',
'<block type="control_repeat"><value name="TIMES"><shadow type="text"/></value></block>',
'<block id="for_each" type="control_for_each"><value name="VALUE"><shadow type="text"/></value></block>',
'',
'<block type="control_stop"><mutation hasnext="true"></mutation><field name="STOP_OPTION">this script</field></block>',
'<block type="control_forever"/>',
'',
'<block type="control_get_counter"/>',
'<block type="control_incr_counter"/>',
'<block type="control_clear_counter"/>',
'',
'<block type="control_wait"><value name="DURATION"><shadow type="text"/></value></block>',
'',
'侦测',
'<block type="sensing_username"/>',
'<block type="sensing_answer"/>',
'<block type="sensing_askandwait"><value name="QUESTION"><shadow type="text"/></value></block>',
'',
'<block type="sensing_keyoptions"/>',
'<block type="sensing_mousedown"/>',
'<block type="sensing_keypressed"><value name="KEY_OPTION"><shadow type="text"/></value></block>',
'<block type="sensing_keypressed"><value name="KEY_OPTION"><shadow type="sensing_keyoptions"/></value></block>',
'',
'<block type="sensing_dayssince2000"/>',
'<block type="sensing_current"/>',
'',
'<block type="sensing_mousex"/>',
'<block type="sensing_mousey"/>',
'<block type="operator_mathop"><field name="OPERATOR">sqrt</field><value name="NUM"><block type="operator_add"><value name="NUM1"><block type="operator_multiply"><value name="NUM1"><block type="operator_subtract"><value name="NUM1"><shadow type="text"/></value><value name="NUM2"><shadow type="text"/></value></block></value><value name="NUM2"><block type="operator_subtract"><value name="NUM1"><shadow type="text"/></value><value name="NUM2"><shadow type="text"/></value></block></value></block></value><value name="NUM2"><block type="operator_multiply"><value name="NUM1"><block type="operator_subtract"><value name="NUM1"><shadow type="text"/></value><value name="NUM2"><shadow type="text"/></value></block></value><value name="NUM2"><block type="operator_subtract"><value name="NUM1"><shadow type="text"/></value><value name="NUM2"><shadow type="text"/></value></block></value></block></value></block></value></block>',
'<block type="operator_add"><value name="NUM1"><block type="operator_multiply"><value name="NUM1"><shadow type="text"><field name="TEXT">90</field></shadow></value><value name="NUM2"><block type="operator_gt"><value name="OPERAND1"><shadow type="text"/></value><value name="OPERAND2"><shadow type="text"/></value></block></value></block></value><value name="NUM2"><block type="operator_mathop"><field name="OPERATOR">atan</field><value name="NUM"><block type="operator_divide"><value name="NUM1"><block type="operator_subtract"><value name="NUM1"><shadow type="text"/></value><value name="NUM2"><shadow type="text"/></value></block></value><value name="NUM2"><block type="operator_subtract"><value name="NUM1"><shadow type="text"/></value><value name="NUM2"><shadow type="text"/></value></block></value></block></value></block></value></block>',
'',
'<block type="sensing_of_object_menu"/>',
'<block type="sensing_of"><value name="OBJECT"><shadow type="sensing_of_object_menu"/></value></block>',
'',
'<block type="sensing_touchingobjectmenu"/>',
'<block type="sensing_distanceto"><value name="DISTANCETOMENU"><shadow type="sensing_distancetomenu"/></value></block>',
'<block type="sensing_touchingobject"><value name="TOUCHINGOBJECTMENU"><shadow type="sensing_touchingobjectmenu"/></value></block>',
'',
'<block type="sensing_touchingcolor"><value name="COLOR"><shadow type="text"/></value></block>',
'<block type="sensing_touchingcolor"><value name="COLOR"><shadow type="colour_picker"><field name="COLOUR">#5cb1d6</field></shadow></value></block>',
'<block type="sensing_coloristouchingcolor"><value name="COLOR"><shadow type="text"/></value><value name="COLOR2"><shadow type="text"/></value></block>',
'<block type="sensing_coloristouchingcolor"><value name="COLOR"><shadow type="colour_picker"><field name="COLOUR">#5cb1d6</field></shadow></value><value name="COLOR2"><shadow type="colour_picker"><field name="COLOUR">#5cb1d6</field></shadow></value></block>',
'',
'注释',
'<block type="procedures_call"><mutation proccode="// %s" argumentids="[&quot;_&quot;]" warp="true"/><value name="_"><shadow type="text"/></value></block>',
'<block type="control_all_at_once"/>',
'',
'<block type="operator_mathop"><field name="OPERATOR"></field><value name="NUM"><shadow type="text"/></value></block>',
'<block type="operator_subtract"><value name="NUM1"><shadow type="text"/></value><value name="NUM2"><shadow type="text"/></value></block>',
'<block type="operator_add"><value name="NUM1"><shadow type="text"/></value><value name="NUM2"><shadow type="text"/></value></block>',
'<block type="operator_subtract"><value name="NUM1"><shadow type="text"/></value><value name="NUM2"><shadow type="operator_mathop"><field name="OPERATOR"></field><value name="NUM"><shadow type="text"/></value></shadow></value></block>',
'<block type="operator_add"><value name="NUM1"><shadow type="operator_mathop"><field name="OPERATOR"></field><value name="NUM"><shadow type="text"/></value></shadow></value><value name="NUM2"><shadow type="text"/></value></block>',
'<block type="operator_letter_of"><value name="STRING"><shadow type="text"/></value><value name="LETTER"><shadow type="colour_picker"><field name="COLOUR">#59C059</field></shadow></value></block>',
'<block type="operator_join"><value name="STRING1"><shadow type="text"/></value><value name="STRING2"><shadow type="operator_letter_of"><value name="STRING"><shadow type="text"/></value><value name="LETTER"><shadow type="colour_picker"><field name="COLOUR">#59C059</field></shadow></value></shadow></value></block>',
'<block type="operator_join"><value name="STRING1"><shadow type="operator_letter_of"><value name="STRING"><shadow type="text"/></value><value name="LETTER"><shadow type="colour_picker"><field name="COLOUR">#59C059</field></shadow></value></shadow></value><value name="STRING2"><shadow type="text"/></value></block>',
'',
'<block type="operator_or"><value name="OPERAND1"><shadow type="argument_editor_boolean"><field name="TEXT"/></shadow></value><value name="OPERAND2"><shadow type="argument_editor_boolean"><field name="TEXT"/></shadow></value></block>',
'<block type="operator_or"><value name="OPERAND1"><shadow type="operator_and"><value name="OPERAND2"><shadow type="argument_editor_boolean"><field name="TEXT"/></shadow></value></shadow></value><value name="OPERAND2"><shadow type="argument_editor_boolean"><field name="TEXT"/></shadow></value></block>',
'<block type="operator_or"><value name="OPERAND1"><shadow type="argument_editor_boolean"><field name="TEXT"/></shadow></value><value name="OPERAND2"><shadow type="operator_and"><value name="OPERAND1"><shadow type="argument_editor_boolean"><field name="TEXT"/></shadow></value></shadow></value></block>',
'',
'事件',
'<block type="event_whenflagclicked"/>',
'<block type="sensing_loudness"/>',
'<block type="sensing_timer"/>',
'<block type="sensing_resettimer"/>',
'<block type="event_whengreaterthan"><field name="WHENGREATERTHANMENU">TIMER</field><value name="VALUE"><shadow type="text"/></value></block>',
'<block type="event_whengreaterthan"><field name="WHENGREATERTHANMENU">TIMER</field><value name="VALUE"><block type="operator_subtract"><value name="NUM1"><shadow type="sensing_timer"/></value><value name="NUM2"><shadow type="text"/></value></block></value></block>',
'',
'<block type="event_broadcast_menu"/>',
'<block type="event_whenbroadcastreceived"/>',
'<block type="event_broadcast"><value name="BROADCAST_INPUT"><shadow type="text"/></value></block>',
'<block type="event_broadcastandwait"><value name="BROADCAST_INPUT"><shadow type="text"/></value></block>',
'<block type="event_broadcast"><value name="BROADCAST_INPUT"><shadow type="event_broadcast_menu"/></value></block>',
'<block type="event_broadcastandwait"><value name="BROADCAST_INPUT"><shadow type="event_broadcast_menu"/></value></block>',
'',
'<block type="event_whenthisspriteclicked"/>',
'<block type="event_whenbackdropswitchesto"/>',
'<block type="event_whentouchingobject"><value name="TOUCHINGOBJECTMENU"><shadow type="sensing_touchingobjectmenu"/></value></block>',
'',
'',
'数据',
'<block type="data_variable"/>',
'<block type="data_setvariableto"><value name="VALUE"><shadow type="text"/></value></block>',
'<block type="data_changevariableby"><value name="VALUE"><shadow type="text"><field name="TEXT">1</field></shadow></value></block>',
'',
'<block type="data_listcontents"/>',
'<block type="data_lengthoflist"/>',
'<block type="data_itemoflist"><value name="INDEX"><shadow type="text"><field name="TEXT">last</field></shadow></value></block>',
'<block type="data_replaceitemoflist"><value name="INDEX"><shadow type="text"><field name="TEXT">last</field></shadow></value><value name="ITEM"><shadow type="text"/></value></block>',
'<block type="data_insertatlist"><value name="INDEX"><shadow type="text"><field name="TEXT">1</field></shadow></value><value name="ITEM"><shadow type="text"/></value></block>',
'',
'<block type="data_addtolist"><value name="ITEM"><shadow type="text"/></value></block>',
'<block type="data_deleteoflist"><value name="INDEX"><shadow type="text"><field name="TEXT">last</field></shadow></value></block>',
'<block type="data_deletealloflist"/>',
'',
'<block type="data_listcontainsitem"><value name="ITEM"><shadow type="text"><field name="TEXT">last</field></shadow></value></block>',
'<block type="data_itemnumoflist"><value name="ITEM"><shadow type="text"/></value></block>',
'',
'动作',
'<block type="motion_direction"/>',
'<block type="motion_goto_menu"/>',
'<block type="motion_pointindirection"><value name="DIRECTION"><shadow type="math_angle"><field name="NUM">90</field></shadow></value></block>',
'<block type="motion_pointtowards"><value name="TOWARDS"><shadow type="motion_goto_menu"><field name="TO">_mouse_</field></shadow></value></block>',
'<block type="motion_turnright"><value name="DEGREES"><shadow type="math_angle"/></value></block>',
'<block type="motion_turnleft"><value name="DEGREES"><shadow type="math_angle"/></value></block>',
'',
'<block type="motion_xposition"/>',
'<block type="motion_yposition"/>',
'<block type="motion_gotoxy"><value name="X"><shadow type="text"/></value><value name="Y"><shadow type="text"/></value></block>',
'<block type="motion_glidesecstoxy"><value name="SECS"><shadow type="text"/></value><value name="X"><shadow type="text"/></value><value name="Y"><shadow type="text"/></value></block>',
'<block type="motion_goto"><value name="TO"><shadow type="motion_goto_menu"><field name="TO">_mouse_</field></shadow></value></block>',
'<block type="motion_glideto"><value name="SECS"><shadow type="text"/></value><value name="TO"><shadow type="motion_glideto_menu"><field name="TO">_mouse_</field></shadow></value></block>',
'<block type="motion_gotoxy"><value name="X"><block type="operator_add"><value name="NUM1"><shadow type="motion_xposition"/></value><value name="NUM2"><shadow type="text"/></value></block></value><value name="Y"><block type="operator_add"><value name="NUM1"><shadow type="motion_yposition"/></value><value name="NUM2"><shadow type="text"/></value></block></value></block>',
'<block type="motion_glidesecstoxy"><value name="SECS"><shadow type="text"/></value><value name="X"><block type="operator_add"><value name="NUM1"><shadow type="motion_xposition"/></value><value name="NUM2"><shadow type="text"/></value></block></value><value name="Y"><block type="operator_add"><value name="NUM1"><shadow type="motion_yposition"/></value><value name="NUM2"><shadow type="text"/></value></block></value></block>',
'',
'<block type="motion_setx"><value name="X"><shadow type="text"/></value></block>',
'<block type="motion_sety"><value name="Y"><shadow type="text"/></value></block>',
'<block type="motion_changexby"><value name="DX"><shadow type="text"/></value></block>',
'<block type="motion_changeyby"><value name="DY"><shadow type="text"/></value></block>',
'<block type="motion_changexby"><value name="DX"><block type="operator_subtract"><value name="NUM1"><shadow type="text"/></value><value name="NUM2"><shadow type="text"/></value></block></value></block>',
'<block type="motion_changeyby"><value name="DY"><block type="operator_subtract"><value name="NUM1"><shadow type="text"/></value><value name="NUM2"><shadow type="text"/></value></block></value></block>',
'',
'<block type="motion_movesteps"><value name="STEPS"><shadow type="text"/></value></block>',
'<block type="motion_gotoxy"><value name="X"><block type="operator_add"><value name="NUM1"><shadow type="motion_xposition"/></value><value name="NUM2"><block type="operator_multiply"><value name="NUM1"><block type="operator_mathop"><field name="OPERATOR">sin</field><value name="NUM"><shadow type="text"/></value></block></value><value name="NUM2"><shadow type="text"/></value></block></value></block></value><value name="Y"><block type="operator_add"><value name="NUM1"><shadow type="motion_yposition"/></value><value name="NUM2"><block type="operator_multiply"><value name="NUM1"><block type="operator_mathop"><field name="OPERATOR">cos</field><value name="NUM"><shadow type="text"/></value></block></value><value name="NUM2"><shadow type="text"/></value></block></value></block></value></block>',
'',
'<block type="motion_ifonedgebounce"/>',
'<block type="motion_setrotationstyle"><field name="STYLE">left-right</field></block>',
'<block type="sensing_setdragmode"/>',
'',
'外观',
'<block type="looks_show"/>',
'<block type="looks_hide"/>',
'',
'<block type="looks_size"/>',
'<block type="looks_setsizeto"><value name="SIZE"><shadow type="text"><field name="TEXT">100</field></shadow></value></block>',
'<block type="looks_changesizeby"><value name="CHANGE"><shadow type="text"/></value></block>',
'',
'<block type="looks_backdrops"/>',
'<block type="looks_costume"><field name="COSTUME">previous costume</field></block>',
'<block type="looks_backdropnumbername"/>',
'<block type="looks_costumenumbername"/>',
'<block type="looks_nextbackdrop"/>',
'<block type="looks_nextcostume"/>',
'<block type="looks_switchbackdropto"><value name="BACKDROP"><shadow type="text"/></value></block>',
'<block type="looks_switchcostumeto"><value name="COSTUME"><shadow type="text"/></value></block>',
'<block type="looks_switchbackdropto"><value name="BACKDROP"><shadow type="looks_backdrops"/></value></block>',
'<block type="looks_switchcostumeto"><value name="COSTUME"><shadow type="looks_costume"><field name="COSTUME">previous costume</field></shadow></value></block>',
'',
'<block type="looks_say"><value name="MESSAGE"><shadow type="text"><field name="TEXT">Test</field></shadow></value></block>',
'<block type="looks_think"><value name="MESSAGE"><shadow type="text"><field name="TEXT">Test</field></shadow></value></block>',
'<block type="looks_sayforsecs"><value name="MESSAGE"><shadow type="text"><field name="TEXT">Test</field></shadow></value><value name="SECS"><shadow type="text"/></value></block>',
'<block type="looks_thinkforsecs"><value name="MESSAGE"><shadow type="text"><field name="TEXT">Test</field></shadow></value><value name="SECS"><shadow type="text"/></value></block>',
'',
'<block type="looks_cleargraphiceffects"/>',
'<block type="looks_seteffectto"><field name="EFFECT">GHOST</field><value name="VALUE"><shadow type="text"/></value></block>',
'<block type="looks_changeeffectby"><field name="EFFECT">GHOST</field><value name="CHANGE"><shadow type="text"/></value></block>',
'',
'<block type="looks_gotofrontback"/>',
'<block type="looks_goforwardbackwardlayers"><value name="NUM"><shadow type="text"><field name="TEXT">1</field></shadow></value></block>',
'',
'<block type="data_showvariable"/>',
'<block type="data_hidevariable"/>',
'<block type="data_showlist"/>',
'<block type="data_hidelist"/>',
'',
'声音',
'<block type="sound_volume"/>',
'<block type="sound_setvolumeto"><value name="VOLUME"><shadow type="text"><field name="TEXT">100</field></shadow></value></block>',
'<block type="sound_changevolumeby"><value name="VOLUME"><shadow type="text"/></value></block>',
'',
'<block type="sound_sounds_menu"/>',
'<block type="sound_stopallsounds"/>',
'<block type="sound_play"><value name="SOUND_MENU"><shadow type="text"/></value></block>',
'<block type="sound_playuntildone"><value name="SOUND_MENU"><shadow type="text"/></value></block>',
'<block type="sound_play"><value name="SOUND_MENU"><shadow type="sound_sounds_menu"/></value></block>',
'<block type="sound_playuntildone"><value name="SOUND_MENU"><shadow type="sound_sounds_menu"/></value></block>',
'',
'<block type="sound_cleareffects"/>',
'<block type="sound_seteffectto"><value name="VALUE"><shadow type="text"/></value></block>',
'<block type="sound_changeeffectby"><value name="VALUE"><shadow type="text"/></value></block>',
'',
'画笔',
'<block type="pen_clear"/>',
'<block type="pen_stamp"/>',
'<block type="pen_penUp"/>',
'<block type="pen_penDown"/>',
'',
'<block type="pen_setPenColorToColor"><value name="COLOR"><shadow type="text"/></value></block>',
'<block type="pen_setPenColorToColor"><value name="COLOR"><shadow type="colour_picker"><field name="COLOUR">#1cbd90</field></shadow></value></block>',
'<block type="pen_setPenColorParamTo"><value name="COLOR_PARAM"><shadow type="pen_menu_colorParam"/></value><value name="VALUE"><shadow type="text"/></value></block>',
'<block type="pen_changePenColorParamBy"><value name="COLOR_PARAM"><shadow type="pen_menu_colorParam"/></value><value name="VALUE"><shadow type="text"/></value></block>',
'',
'<block type="pen_setPenSizeTo"><value name="SIZE"><shadow type="text"/></value></block>',
'<block type="pen_changePenSizeBy"><value name="SIZE"><shadow type="text"/></value></block>',
].map(o=>o instanceof Object?o:o==''?'---':o[0]=='<'?{blockType:'xml',xml:o}:{blockType:'label',text:o})}}})